import { Command } from 'commander';
import Handlebars from 'handlebars';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getConfig, getTemplatesDir } from '../config/config.js';
import { log } from '../utils/logger.js';
import { gradeLabel, gradeColor, formatGrade } from '../utils/grading.js';
import { pitchTypeName } from '../adapters/types.js';
import { query as runQuery } from './query.js';
import { getStdinAdapter } from '../adapters/index.js';
import { readStdin } from '../utils/stdin.js';
import { generateReportGraphs } from '../viz/embed.js';
import {
  getReportTemplate,
  listReportTemplates,
  type Audience,
} from '../templates/reports/registry.js';
import { CLI_VERSION } from '../utils/version.js';

export interface ReportOptions {
  template: string;
  player?: string;
  team?: string;
  season?: number;
  audience?: Audience;
  format?: 'markdown' | 'json';
  validate?: boolean;
  stdin?: boolean;
  /**
   * When true (default), the command throws if any data requirement marked
   * `required: true` fails, causing the CLI to exit non-zero. Set to false to
   * preserve the older lenient behavior of emitting a stub-shell report with
   * placeholders for missing data. (BBDATA-001)
   */
  strict?: boolean;
}

export interface ReportResult {
  content: string;
  formatted: string;
  validation?: ValidationResult;
  meta: {
    template: string;
    player: string;
    audience: Audience;
    season: number;
    dataSources: string[];
  };
}

export interface ValidationResult {
  passed: boolean;
  issues: { severity: 'error' | 'warning'; message: string }[];
}

// Register Handlebars helpers
Handlebars.registerHelper('grade', (value: number) => formatGrade(value));
Handlebars.registerHelper('gradeLabel', (value: number) => gradeLabel(value));
Handlebars.registerHelper('pitchType', (code: string) => pitchTypeName(code));
Handlebars.registerHelper('formatStat', (value: number, decimals: number) => {
  if (value === null || value === undefined) return '—';
  return typeof decimals === 'number' ? Number(value).toFixed(decimals) : String(value);
});
Handlebars.registerHelper('compare', (value: number, leagueAvg: number) => {
  if (value === null || value === undefined) return '—';
  const diff = value - leagueAvg;
  const pct = leagueAvg !== 0 ? ((diff / leagueAvg) * 100).toFixed(1) : '0';
  return diff > 0 ? `+${pct}%` : `${pct}%`;
});
Handlebars.registerHelper('ifGt', function (this: unknown, a: number, b: number, options: any) {
  return a > b ? options.fn(this) : options.inverse(this);
});
Handlebars.registerHelper('svgOrEmpty', (svg: string) =>
  new Handlebars.SafeString(svg ?? ''),
);

const __dirname = dirname(fileURLToPath(import.meta.url));
const BUNDLED_TEMPLATES_DIR = join(__dirname, '..', 'templates', 'reports');

function loadTemplate(templateFile: string): string {
  // Check user overrides first
  const userDir = join(getTemplatesDir(), 'reports');
  const userPath = join(userDir, templateFile);
  if (existsSync(userPath)) {
    return readFileSync(userPath, 'utf-8');
  }

  // Fall back to bundled templates
  const bundledPath = join(BUNDLED_TEMPLATES_DIR, templateFile);
  if (existsSync(bundledPath)) {
    return readFileSync(bundledPath, 'utf-8');
  }

  // Generate a basic template structure from the template definition
  return generateFallbackTemplate(templateFile);
}

function generateFallbackTemplate(templateFile: string): string {
  // When no .hbs file exists yet, generate markdown structure from the template definition
  const templateId = templateFile.replace('.hbs', '');
  const template = getReportTemplate(templateId);

  if (!template) return '# Report\n\n{{data}}';

  const sections = template.requiredSections
    .map((s) => `## ${s}\n\n{{!-- ${s} data goes here --}}\n*Data pending*\n`)
    .join('\n');

  return `# ${template.name}\n\n**Player:** {{player}}\n**Season:** {{season}}\n**Audience:** {{audience}}\n**Generated:** {{date}}\n\n---\n\n${sections}\n\n---\n*Generated by bbdata CLI · Data sources: {{sources}}*\n`;
}

/**
 * Programmatic API — skills and agents call this directly.
 */
export async function report(options: ReportOptions): Promise<ReportResult> {
  // Pre-load stdin data once for all sub-queries
  if (options.stdin) {
    const raw = await readStdin();
    const adapter = getStdinAdapter();
    adapter.load(raw);
  }

  const config = getConfig();
  const audience = options.audience ?? (config.defaultAudience as Audience);

  const template = getReportTemplate(options.template);
  if (!template) {
    const available = listReportTemplates().map((t) => `  ${t.id} — ${t.description}`).join('\n');
    throw new Error(`Unknown report template "${options.template}". Available:\n${available}`);
  }

  const season = options.season ?? new Date().getFullYear();
  const player = options.player ?? 'Unknown';
  const team = options.team ?? '';

  // Gather data from required queries
  const dataResults: Record<string, unknown> = {};
  const dataSources: string[] = [];
  // BBDATA-001: collect failures so we can exit non-zero in strict mode.
  const failedRequired: { queryTemplate: string; message: string }[] = [];

  for (const req of template.dataRequirements) {
    try {
      const result = await runQuery({
        template: req.queryTemplate,
        player: options.player,
        team: options.team,
        season,
        format: 'json',
        ...(options.stdin ? { source: 'stdin' } : {}),
      });
      dataResults[req.queryTemplate] = result.data;
      if (!dataSources.includes(result.meta.source)) {
        dataSources.push(result.meta.source);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (req.required) {
        log.warn(`Required data "${req.queryTemplate}" failed: ${message}`);
        failedRequired.push({ queryTemplate: req.queryTemplate, message });
      }
      dataResults[req.queryTemplate] = null;
    }
  }

  // BBDATA-001: fail loudly in strict mode (default) so scripts and CI see
  // required-data failures as errors rather than silent stub-shell success.
  const strict = options.strict ?? true;
  if (strict && failedRequired.length > 0) {
    const detail = failedRequired
      .map((f) => `  - ${f.queryTemplate}: ${f.message}`)
      .join('\n');
    throw new Error(
      `Report "${template.id}" cannot be generated — ${failedRequired.length} required data query(s) failed:\n${detail}\n` +
        `Pass --no-strict to emit a stub-shell report with placeholders instead.`,
    );
  }

  // Generate any graphs this report embeds (failures degrade gracefully to '')
  const graphs = await generateReportGraphs(
    template.id,
    player,
    season,
    audience,
    { stdin: options.stdin },
  );

  // Load and compile Handlebars template
  const hbsSource = loadTemplate(template.templateFile);
  const compiled = Handlebars.compile(hbsSource);

  // Render
  const content = compiled({
    player,
    team,
    season,
    audience,
    date: new Date().toISOString().split('T')[0],
    sources: dataSources.join(', ') || 'none',
    cliVersion: CLI_VERSION,
    data: dataResults,
    graphs,
    ...dataResults,
  });

  // Validate if requested
  let validation: ValidationResult | undefined;
  if (options.validate) {
    validation = validateReport(content, template.requiredSections);
  }

  const formatted = options.format === 'json'
    ? JSON.stringify(
        {
          content,
          // Structured query results keyed by queryTemplate id (BBDATA-014).
          // Agent consumers can read these directly instead of regex-parsing `content`.
          sections: dataResults,
          validation,
          meta: { template: template.id, player, audience, season, dataSources },
        },
        null,
        2,
      ) + '\n'
    : content + '\n';

  return {
    content,
    formatted,
    validation,
    meta: {
      template: template.id,
      player,
      audience,
      season,
      dataSources,
    },
  };
}

function validateReport(content: string, requiredSections: string[]): ValidationResult {
  const issues: ValidationResult['issues'] = [];

  // Check required sections are present
  for (const section of requiredSections) {
    if (!content.includes(section)) {
      issues.push({ severity: 'warning', message: `Missing section: "${section}"` });
    }
  }

  // Check for common AI hallucination patterns
  if (content.includes('Data pending') || content.includes('data goes here')) {
    issues.push({ severity: 'error', message: 'Report contains placeholder text — data was not populated' });
  }

  // Check for generic language
  const genericPhrases = ['shows promise', 'solid player', 'good potential', 'talented athlete'];
  for (const phrase of genericPhrases) {
    if (content.toLowerCase().includes(phrase)) {
      issues.push({ severity: 'warning', message: `Generic language detected: "${phrase}" — be more specific` });
    }
  }

  // Check minimum length
  if (content.length < 200) {
    issues.push({ severity: 'warning', message: 'Report seems too short — may be missing content' });
  }

  return {
    passed: issues.filter((i) => i.severity === 'error').length === 0,
    issues,
  };
}

/**
 * CLI registration — Commander calls this.
 */
export function registerReportCommand(program: Command): void {
  program
    .command('report [template]')
    .description('Generate scouting reports using pre-built templates')
    .option('-p, --player <name>', 'Player name')
    .option('-t, --team <code>', 'Team abbreviation')
    .option('-s, --season <year>', 'Season year', String(new Date().getFullYear()))
    .option('-a, --audience <role>', 'Target audience: coach, gm, scout, analyst')
    .option('-f, --format <fmt>', 'Output: markdown, json', 'markdown')
    .option('--validate', 'Run validation checklist on the report')
    .option('--no-strict', 'Do not exit non-zero when required data queries fail (emit stub-shell output)')
    .option('--stdin', 'Read pre-fetched JSON data from stdin instead of fetching from APIs')
    .addHelpText('after', `
Examples:
  bbdata report pro-pitcher-eval --player "Corbin Burnes"
  bbdata report advance-sp --player "Gerrit Cole" --audience coach --validate
  bbdata report trade-target-onepager --player "Vladimir Guerrero Jr." --audience gm

Available templates:
  Pro Scouting:    pro-pitcher-eval, pro-hitter-eval, relief-pitcher-quick
  Amateur:         college-pitcher-draft, college-hitter-draft, hs-prospect
  Advance:         advance-sp, advance-lineup
  Player Dev:      dev-progress, post-promotion
  Executive:       trade-target-onepager, draft-board-card
`)
    .action(async (templateId, opts) => {
      if (!templateId) {
        const templates = listReportTemplates();
        log.data('\nAvailable report templates:\n\n');
        for (const t of templates) {
          log.data(`  ${t.id.padEnd(28)} ${t.description}\n`);
        }
        log.data('\nUsage: bbdata report <template> --player "Name" [options]\n\n');
        return;
      }

      try {
        const result = await report({
          template: templateId,
          player: opts.player,
          team: opts.team,
          season: opts.season ? parseInt(opts.season) : undefined,
          audience: opts.audience as Audience,
          format: opts.format,
          validate: opts.validate,
          stdin: opts.stdin,
          strict: opts.strict,
        });

        log.data(result.formatted);

        if (result.validation && !result.validation.passed) {
          log.warn('Validation issues found:');
          for (const issue of result.validation.issues) {
            const prefix = issue.severity === 'error' ? '  ✗' : '  ⚠';
            log.warn(`${prefix} ${issue.message}`);
          }
        }
      } catch (error) {
        log.error(error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
      }
    });
}
